version: 0.2
env:
  variables:
    MAJOR: 1
    MINOR: 0
  build-version: artifact-${MAJOR}.${MINOR}     
phases:
  build:
    commands:
      - rspec HelloWorld_spec.rb
artifacts:
  files:
    - '**/*'
  name: ${CODEBUILD_BUILD_VERSION} 
